/// Flutter icons CustomHamburger
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomHamburger
///      fonts:
///       - asset: fonts/CustomHamburger.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomHamburger {
  CustomHamburger._();

  static const _kFontFam = 'CustomHamburger';
  static const String? _kFontPkg = null;

  static const IconData hamburger_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
