/// Flutter icons CustomTacos
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomTacos
///      fonts:
///       - asset: fonts/CustomTacos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomTacos {
  CustomTacos._();

  static const _kFontFam = 'CustomTacos';
  static const String? _kFontPkg = null;

  static const IconData taco_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
