/// Flutter icons CustomShopping
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomShopping
///      fonts:
///       - asset: fonts/CustomShopping.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomShopping {
  CustomShopping._();

  static const _kFontFam = 'CustomShopping';
  static const String? _kFontPkg = null;

  static const IconData shopping_bag_icon_icons_com_63448 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
