/// Flutter icons CustomSweet
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomSweet
///      fonts:
///       - asset: fonts/CustomSweet.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomSweet {
  CustomSweet._();

  static const _kFontFam = 'CustomSweet';
  static const String? _kFontPkg = null;

  static const IconData pie_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
