/// Flutter icons CustomSoup
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomSoup
///      fonts:
///       - asset: fonts/CustomSoup.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomSoup {
  CustomSoup._();

  static const _kFontFam = 'CustomSoup';
  static const String? _kFontPkg = null;

  static const IconData chinese_food_meal_cuisine_noodle_soup_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
