/// Flutter icons CustomHome
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomHome
///      fonts:
///       - asset: fonts/CustomHome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomHome {
  CustomHome._();

  static const _kFontFam = 'CustomHome';
  static const String? _kFontPkg = null;

  static const IconData home_icon_227229 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
